#PBS -N pan_ltr_class
#PBS -l nodes=1:ppn=5,walltime=720:00:00:00
#PBS -q defaultApp
#PBS -j oe
#PBS -o log_ltr_class

echo "Starting"
date
hostname

cd $PBS_O_WORKDIR

filename=${genome##*/}
speciesname=${filename%%.*}
ltr="/public/home/huangyj/anaconda3/envs/LAI/bin/LTR_retriever"

source activate /public/home/huangyj/anaconda3/envs/repeatscout
##job area
##Step1
perl /public/home/huangyj/software/RepeatModeler-master/02_Ltr_and_classfier.pl -threads 5 -database $speciesname -LTRStruct

echo "base build"
##Step2
#lib_dir=`grep "Using output directory" $log | cut -f 5 -d " "`
lib_dir=`ls |grep -E "^RM_"`
lib="$lib_dir/consensi.fa.classified"
#lib="HDR7_genome_version5_full-families.fa"
##argument -lib: produced by steps above.
if [ -f $lib ] ; then
:
#RepeatMasker -pa 8 -qq -e ncbi -lib $lib -gff $genome -dir ./
fi
conda deactivate
echo "Finished"
date

