#PBS -N pan_deepTE_class
#PBS -l nodes=1:ppn=2,walltime=720:00:00:00,mem=50g
#PBS -q defaultApp
#PBS -j oe
#PBS -o log_deepTE_class

echo "Starting"
date
hostname

cd $PBS_O_WORKDIR

#repfa=''
#sp=''

source activate /public/home/huangyj/anaconda3/envs/deepTE
##job area
deep_dir="/public/home/huangyj/software/DeepTE-master"
Class_table="/public/home/huangyj/pan_rice/Class_convert_table.txt"
repbase_ory="/public/home/huangyj/pan_rice/oryrep_modi.ref"
script1="/public/home/huangyj/pan_rice/_03_deepTE_idconvert_step1.py"
script2="/public/home/huangyj/pan_rice/_03_deepTE_idconvert_step2.py"
script3="/public/home/huangyj/pan_rice/_03_deepTE_idconvert_step3.py"
##Step1
mkdir -p deepTE_tmp
mkdir -p domain_out
#python ${deep_dir}/DeepTE_domain.py -d deepTE_tmp  -o domain_out -i $repfa -s /public/home/huangyj/software/DeepTE-master/supfile_dir --hmmscan /public/home/huangyj/anaconda3/envs/deepTE/bin/hmmscan
echo ${sp} "DeepTE doamin search complete!"
##Step2
mkdir -p TE_classify_out
#python ${deep_dir}/DeepTE.py -o TE_classify_out -d deepTE_tmp -i $repfa -m_dir /public/home/huangyj/Database/Plants_model -sp P -modify domain_out/opt_te_domain_pattern.txt

echo ${sp} "DeepTE search complete!"

##step3 id convert
python $script1 $Class_table TE_classify_out/opt_DeepTE.txt  
cut -f 1 TE_classify_out/opt_DeepTE.txt | paste - deepTE_idconverted.id > id.convert
python $script3 $repfa id.convert ${sp}_new_classfied_concensis.fa

conda deactivate
echo "Finished"
date

