#PBS -N pan_repeatmask
#PBS -l nodes=1:ppn=20,walltime=720:00:00:00,mem=100g
#PBS -q defaultApp
#PBS -j oe
#PBS -o log_repeat_masker

echo "Starting"
date
hostname

cd $PBS_O_WORKDIR

#export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib64:$LD_LIBRARY_PATH
##set arguments
filename=${genome##*/}
speciesname=${filename%%.*}
source activate /public/home/huangyj/anaconda3/envs/repeatscout
##job area
##Step2
#lib_dir=`grep "Using output directory" $log | cut -f 5 -d " "`
if [ -f $lib ] ; then
:
RepeatMasker -pa 8 -qq -e ncbi -lib $lib -gff $genome -dir ./
fi
conda deactivate
echo "Finished"
date

